<log type="Session" name="TEST-DUYENDT-PC:LQA" at="2023-06-16 10:26:34.544"/>
<log type="Test" name="TC05_DataDriven" status="Info"  at="2023-06-16 10:26:35.683"><data type="text">Test Started: C:\Users\LQA\Documents\My Rapise Tests\PoM\TC05_DataDriven\Main.js</data>
</log>
<log type="Message" name="Starting scenario: Test" status="Info"  at="2023-06-16 10:26:35.685"/>
<log type="Assert" name="Failure in Test" status="Fail"  at="2023-06-16 10:26:35.689"><data type="text" caption="Exception">Error(-2147024894): </data>
<data type="link" url="C:\Users\LQA\Documents\My Rapise Tests\PoM\TC05_DataDriven\Main.js(4,1)" text="C:\Users\LQA\Documents\My Rapise Tests\PoM\TC05_DataDriven\Main.js(4,1)"/>
<data type="text">Global.DoRunTestSet(&quot;../Scripts/TestSetCritial.js&quot;);</data>
</log>
<log type="Test" name="TC05_DataDriven" status="Fail" closed="TC05_DataDriven" _guid="undefined"  at="2023-06-16 10:26:35.691" comment="Passed:0 Failed:1 Time:0.145s" />
